# driver for the AWUS036ACH
sudo apt install realtek-rtl88xxau-dkms -y
# wire shark coloring rules for 802.1x
echo '# DO NOT EDIT THIS FILE!  It was created by Wireshark' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.ba_req@wlan.fc.type_subtype == 0x18@[65535,65535,65535][50372,41120,0]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.ps_poll@wlan.fc.type_subtype == 0x1a@[65535,65535,65535][36281,18871,45656]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.qos_null@wlan.fc.type_subtype == 0x2c@[65535,65535,65535][36281,18871,45656]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.null_data@wlan.fc.type_subtype == 0x24@[65535,65535,65535][36281,18871,45656]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@EAPOL@eapol@[65535,65535,65535][8611,29490,4718]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.cts@wlan.fc.type_subtype == 0x1c@[65535,65535,65535][22835,8716,22937]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@EAP@eap@[65535,65535,65535][8611,29490,4718]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.action@wlan.fc.type_subtype == 13@[65535,65535,65535][14352,42817,47840]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.reassoc_response@wlan.fc.type_subtype == 0x03@[65535,65535,65535][11245,28835,12627]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.reassoc_request@wlan.fc.type_subtype == 0x02@[65535,65535,65535][33270,20636,43908]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.beacon@wlan.fc.type_subtype==0x08@[65535,65535,65535][4029,15058,38923]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.assoc_req@wlan.fc.type_subtype==0x0000@[65535,65535,65535][22846,37696,54830]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.assoc_res@wlan.fc.type_subtype==0x01@[65535,65535,65535][20046,39578,1542]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.probe_req@wlan.fc.type_subtype==0x04@[65535,65535,65535][52798,0,0]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.probe_res@wlan.fc.type_subtype==0x05@[65535,65535,65535][44438,23795,5124]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.data@wlan.fc.type_subtype == 0x20@[65535,65535,65535][4033,38493,41723]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.ack@wlan.fc.type_subtype == 0x1d || wlan.fc.type_subtype == 0x19@[65535,65535,65535][62965,31097,0]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.deauth@wlan.fc.type_subtype == 0x0c@[65535,65535,65535][64005,3876,2560]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.auth@wlan.fc.type_subtype==0x0b@[65535,65535,65535][55923,3914,51836]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
echo '@wlan.qos_data@wlan.fc.type_subtype == 0x28@[65535,65535,65535][18754,41068,41068]' >> /home/vagrant/install-scripts/wireshark-802.1x-coloring-rules.txt
# coWPAtty for creating rainbow tables
sudo apt install coWPAtty
# bettercap wifi, bluetooth, etc
sudo apt install bettercap
# kismet
sudo apt install kismet
# for firewall rules
sudo apt install nftables
# load balancer for nfttables
sudo apt install nftlb
# rogue ap's
sudo apt install hostapd-mana
# freeradius
sudo apt -y install freeradius
# easier rogue ap's(less config)
sudo apt install hostapd-wpe
# asleap for cracking
sudo apt install asleap
